### ISSUE TITLE
GSIM Specification (with implementation discussion)

### ISSUE THREAD

**Issue by FlavioRizzolo** [UNECE/GSIMRevision#10]
GSIM is a conceptual model that can be used for business level (e.g. subject matter experts) discussions and to implement with other metadata standards, e.g. DDI, SDMX, PROV, DCAT, etc. For the latter, some sort of **implementation guide** would help architects and developers use GSIM to guide their technical solutions. This guide would **not** deal with the actual mapping to implementation standards, except for a few small illustrative examples. Rather, it will provide the missing information that people developing the mappings will need, perhaps via viewpoints, use cases, etc. 

Possibly related to issue [Additional dimension / categorization of GSIM classes #8](https://github.com/UNECE/GSIMRevision/issues/8)

**Comment by InKyungChoi** [comment]
Some materials

- Business Group and Exchange Group "in action": https://github.com/UNECE/GSIMRevision/discussions/15
- Referential metadata part: https://github.com/UNECE/GSIMRevision/issues/6

**Comment by InKyungChoi** [comment]
Some use cases (to be compiled further)

1. Related Register: Create sample from register as frame, use register for calculate weights, use register
2. Related Referential Metadata Set: Produce dissemination product (data and quality reporting document)
3. Related Statistical Program: Create new statistical program based on new user needs

Templates for use cases?
- Use case description: Create sample from register as frame 
- Relevant GSBPM sub-process: 2.4 (design frame and sample) -> 4.1 (create frame and select sample)
- GSIM classes: Register, Data Sets, etc.

**Comment by InKyungChoi** [comment]
I am thinking now, instead of developing a new user guide, we should update and extend the [GSIM Specification](https://statswiki.unece.org/display/gsim/GSIM+Specification). 

Excluding annex, the main content itself is about 35 pages which contains very useful (and still valid for the most part) information. 

For examples, I am thinking the concrete examples around Referential Metadata Set can go to [Chapter III-K Referential Metadata Sets](https://statswiki.unece.org/display/gsim/III.+Foundational+Information#III.FoundationalInformation-_Toc375075370), examples around Register can go into Chapter II, etc. 

The last version of Specification we had is with previous GSIM v1.1, from 2013, and it was not updated during the last revision (GSIM v1.2, from 2018).

**Comment by InKyungChoi** [comment]
I uploaded the version I am working on as editable google doc here: https://docs.google.com/document/d/1pYmOVfmXR2pQEqjCmI-5WVi2qgkjt1GJ/edit?usp=sharing&ouid=114335116280732994204&rtpof=true&sd=true

**Comment by FlavioRizzolo** [comment]
From Hungary: 

> Suggestion to map the structure of actual statistical products (reference to SDMX?), e.g.:
> data table = Data Set;
> quality report = Referential Metadata Set;
> yearbook = Information Set – what is the structure of Information Set?

I suggest to include a discussion on the topic, perhaps in the use cases section.
