### ISSUE TITLE
Consider removing/redefining Change Event Tuple (Base Group)

### ISSUE THREAD

**Issue by FlavioRizzolo** [UNECE/GSIMRevision#39]
It's unclear what's the role of Change Event Tuple since it has no attributes and the information it conveys, i.e. source and target Identifiable Artifacts, could be maintained directly in the in Change Event.

This is also part of the feedback from Canada (issue https://github.com/UNECE/GSIMRevision/issues/13 .4)

**Proposal**: remove class and move source and target to Change Event.

**Comment by InKyungChoi** [comment]
See updated version based on the last meeting https://github.com/UNECE/GSIMRevision/discussions/40 

![image](https://user-images.githubusercontent.com/10498769/219704811-1b04b8e2-3181-444f-a7a2-476cbf3d8974.png)

**Comment by FrancineK** [comment]
1. Agree with point 1. I was going to propose that we use GSIM terms for tasks (process steps) and business logic/control flow (process control)
2. x
3. **Change Event** **_triggers_** a **Process Step**. I think we should modify the definition of Role so we can leave that association to a Business Process through the relationship between **Agent In Role** and **Identifiable Artefacts**: **responsible function, _associated to an Agent,_ involved in a Identifiable Artefact**. The reason is, the "Role" of "Owner" can be involved directly in a Dataset (this is also supported by Prov-O, prov:wasAttributedTo), the role of Maintainer in a Classification.

**Comment by FrancineK** [comment]
The Referential Metadata Subject should be Referential Metadata Attribute

**Comment by FlavioRizzolo** [comment]
To be implemented in EA UML.
